# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(635, 459)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_lable = QtWidgets.QLabel(self.centralwidget)
        self.input_lable.setGeometry(QtCore.QRect(60, 40, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_lable.setFont(font)
        self.input_lable.setObjectName("input_lable")
        self.word_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.word_Edit.setGeometry(QtCore.QRect(240, 40, 231, 31))
        self.word_Edit.setObjectName("word_Edit")
        self.count_label = QtWidgets.QLabel(self.centralwidget)
        self.count_label.setGeometry(QtCore.QRect(60, 110, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.count_label.setFont(font)
        self.count_label.setObjectName("count_label")
        self.word_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.word_radio.setGeometry(QtCore.QRect(60, 170, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.word_radio.setFont(font)
        self.word_radio.setObjectName("word_radio")
        self.csv_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.csv_radio.setGeometry(QtCore.QRect(330, 170, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.csv_radio.setFont(font)
        self.csv_radio.setObjectName("csv_radio")
        self.file_label = QtWidgets.QLabel(self.centralwidget)
        self.file_label.setGeometry(QtCore.QRect(60, 230, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.file_label.setFont(font)
        self.file_label.setObjectName("file_label")
        self.quit_bt = QtWidgets.QPushButton(self.centralwidget)
        self.quit_bt.setGeometry(QtCore.QRect(500, 360, 93, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.quit_bt.setFont(font)
        self.quit_bt.setObjectName("quit_bt")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 300, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.filepath_input = QtWidgets.QLineEdit(self.centralwidget)
        self.filepath_input.setGeometry(QtCore.QRect(150, 290, 321, 31))
        self.filepath_input.setObjectName("filepath_input")
        self.save_bt = QtWidgets.QPushButton(self.centralwidget)
        self.save_bt.setGeometry(QtCore.QRect(60, 360, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.save_bt.setFont(font)
        self.save_bt.setObjectName("save_bt")
        self.fileName_input = QtWidgets.QLineEdit(self.centralwidget)
        self.fileName_input.setGeometry(QtCore.QRect(150, 230, 321, 31))
        self.fileName_input.setObjectName("fileName_input")
        self.inputok_bt = QtWidgets.QPushButton(self.centralwidget)
        self.inputok_bt.setGeometry(QtCore.QRect(500, 40, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.inputok_bt.setFont(font)
        self.inputok_bt.setObjectName("inputok_bt")
        self.choose_bt = QtWidgets.QPushButton(self.centralwidget)
        self.choose_bt.setGeometry(QtCore.QRect(500, 290, 93, 28))
        self.choose_bt.setObjectName("choose_bt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 635, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "裁判文书数据采集系统"))
        self.input_lable.setText(_translate("MainWindow", "输入采集的关键字:"))
        self.count_label.setText(_translate("MainWindow", ""))
        self.word_radio.setText(_translate("MainWindow", "保存为word"))
        self.csv_radio.setText(_translate("MainWindow", "保存为excel"))
        self.file_label.setText(_translate("MainWindow", "文件名："))
        self.quit_bt.setText(_translate("MainWindow", "退出"))
        self.label_2.setText(_translate("MainWindow", "文件路径："))
        self.save_bt.setText(_translate("MainWindow", "开始下载"))
        self.inputok_bt.setText(_translate("MainWindow", "确定"))
        self.choose_bt.setText(_translate("MainWindow", "浏览"))

